### PR TITLE
Anchor headings

### PR DESCRIPTION
**Pull request by micahl**
Using https://github.com/allejo/jekyll-anchor-headings and [this example](https://github.com/allejo/jekyll-anchor-headings/wiki/Examples#github-style-octicon-links) to get the fancy octicon.

Preview how the changes appear here: https://micahl.github.io/iot-identity-service/

### CODE REVIEW

**Comment by gordonwang0** [comment]
I don't see the anchor headings anywhere in the generated docs. Could you link an example?

**Comment by micahl** [comment]
@gordonwang0 try again. I had switched my repo settings for Pages and forgot to switch it back to the branch for this PR.  Should be apparent now when hovering over a title.

**Review by gordonwang0 — APPROVED** [review]

**Comment by arsing** [comment]
@micahl You also don't need to merge master manually. The bot will do it when you apply the label.

**Comment by micahl** [comment]
I'm constantly learning.  :)  Adding the label...

**Pull request merged**
