### PR TITLE
Using unix sockets in priority

### PR DESCRIPTION
**Pull request by huguesBouvier**
Workload manager creates on unix socket per module.
The current code will try to use a systemd socket for each one.

### CODE REVIEW

**Comment by arsing** [comment]
Preferring systemd sockets is how it's supposed to be. Why are you making this change?

**Comment by huguesBouvier** [comment]
> Preferring systemd sockets is how it's supposed to be. Why are you making this change?

This is to for the workload manager. Worload manager is creating unix socket, so with the current code, when it creates a socket for a new module, it tries to match it with systemd and we gets the error message:"multiple systemd sockets found".

**Comment by huguesBouvier** [comment]
> > Preferring systemd sockets is how it's supposed to be. Why are you making this change?
> 
> This is to for the workload manager. Worload manager is creating unix socket, so with the current code, when it creates a socket for a new module, it tries to match it with systemd and we gets the error message:"multiple systemd sockets found".

This is now used by edged which requires more than one socket

**Comment by arsing** [comment]
Sure. But edged still uses systemd sockets. and the four services in this repo still use systemd sockets.

**Comment by huguesBouvier** [comment]
> Sure. But edged still uses systemd sockets. and the four services in this repo still use systemd sockets.

Right now it doesn't work for unix socket. It tries to use systemd because it is there in priority. Let's talk about that on teams instead, it will be faster than posting.

**Pull request closed without merging**
