### PR TITLE
Remove identityd "get trust bundle" API.

### PR DESCRIPTION
**Pull request by arsing**
This was an undocumented and unimplemented stub; it always returned no certs.

Since it was undocumented and unimplemented, we don't consider this
a breaking change that necessitates a new API version.

### CODE REVIEW

**Review by varunpuranik — CHANGES_REQUESTED** [review]
I would like to check with Shiproom once if this is okay.

**Review by huguesBouvier — APPROVED** [review]
LGTM. One failed test to check, real or flaky.

**Review by gordonwang0 — APPROVED** [review]
I wasn't aware that this was a stub and was using it in the edged tokio refactor. But LGTM.

**Comment by arsing** [comment]
@varunpuranik

>I would like to check with Shiproom once if this is okay.

Well, the alternative is we leave it as a stub, then implement the IS-scoped trust bundle you and I talked about in the call, and reuse this stub for that.

---

@gordonwang0

It would be good to avoid functional changes as part of your refactor.

For this specific case, yes edged has its own config for the trust bundle's cert ID (set by `iotedge config apply`) which it uses to get the cert from certd directly.

**Comment by arsing** [comment]
Not doing this right now.

**Pull request closed without merging**
