### PR TITLE
Cherry-pick packaging changes

### PR DESCRIPTION
**Pull request by gordonwang0**

### CODE REVIEW

**Comment by gordonwang0** [comment]
Looking at the history between release/1.2 and master, it seems like it's ok to import all the changes from master to release/1.2. I can do a git reset of release/1.2 to master.

**Comment by arsing** [comment]
Did we already release rc4? So that we don't have to worry about adding more untested changes to it.

If yes, then I'm fine with `reset`ing it.

**Comment by daprilik** [comment]
(I too am in favor of simply resetting the branch)

**Comment by gordonwang0** [comment]
Aside from these packaging changes, resetting would bring in the some doc fixes and 347a1e6f2b61e50978721b8d9c25bde0af61f684. So I think it's fine to reset. We'll need a new rc4 package anyways because we need the package versioning update here.

**Pull request closed without merging**
