### PR TITLE
Update toolchain to 1.57 and 2021 edition

### PR DESCRIPTION
**Pull request by vadim-kovalyov**
Update toolchain to 1.57. and rust edition to 2021.

### CODE REVIEW

**Comment by arsing** [comment]
If you're going to update it, you might as well update it to latest, including switching to E2021 and making clippy fixes? Why bump the toolchain just to have the *option* of using E2021, instead of actually using it?

**Comment by vadim-kovalyov** [comment]
> If you're going to update it, you might as well update it to latest, including switching to E2021 and making clippy fixes? Why bump the toolchain just to have the _option_ of using E2021, instead of actually using it?

Sure, I tried that and, surprisingly, there were not a lot of errors. Since I don't have much context on this repo - the three errors I saw I fixed with `allow` attributes. @arsing please suggest better fix if needed, and I'll do that.

**Comment by arsing** [comment]
The `large_enum_variant` one is fine. We have a bunch of them already.

Is the `dead_code` one because most of the fields are not used? I guess they made `#[derive(Debug)]` not count as a use any more unless Debug formatting is actually used (which is sensible).

So rather than `#[allow(dead_code)]`'ing it, I think it would be better to do:

```diff,rust
     let packet = Packet::parse(buf, sntp_epoch);
-    #[cfg(test)]
-    let packet = dbg!(packet);
+    log::debug!("Received SNTP packet {:?}", packet);

```

**Comment by vadim-kovalyov** [comment]
> ```diff
> log::debug!("Received SNTP packet {:?}", packet);
> ```

That did not help, unfortunately, unless I manually implement `Debug` (which does not make sense IMHO).

**Comment by arsing** [comment]
Strange. Let's deal with it later then.

**Review by arsing — APPROVED** [review]

**Comment by arsing** [comment]
>Strange. Let's deal with it later then.

Reason for the error: https://github.com/rust-lang/rust/issues/88900

An annoying change. So until they give a better way to opt out, `#[allow(dead_code)]` on each affected struct seems fine to me.

**Pull request merged**
