### PR TITLE
Update version check for 1.2.0

### PR DESCRIPTION
**Pull request by gordonwang0**
Updates the version check for the latest https://raw.githubusercontent.com/Azure/azure-iotedge/master/latest-versions-non-lts.json

### CODE REVIEW

**Comment by arsing** [comment]
It was supposed to be `aziot`. Why change the old code to match the new file instead of writing the new file to match the old code?

**Comment by gordonwang0** [comment]
Consistency with the package name. But sure, it's fine to keep it aziot.

**Comment by arsing** [comment]
Consistency with the package name is fine. In that case make sure to change the first one to `aziot-edge` too.

**Comment by gordonwang0** [comment]
Ok, I'll do that.

**Review by arsing — APPROVED** [review]

**Pull request merged**
