### PR TITLE
add aziotctl system stop (#176)

### PR DESCRIPTION
**Pull request by lfitchett**
Cherry-pick to 1.2 branch

### CODE REVIEW

**Comment by arsing** [comment]
No need. We're just going to `reset --hard` it again.

**Comment by lfitchett** [comment]
@daprilik has a commit after mine that requires changes to iotedge to work. When I cherry-pick my iotedge changes into the 1.2 branch, I was expecting the aziot to not have his changes. (I'm assuming that the iotedge 1.2 branch points to this 1.2 branch).

**Comment by arsing** [comment]
1. Again, there is no need to c-p anything to i-i-s/release/1.2. It will be `reset --hard`'d to `i-i-s/main`. You can do it right now if you want.

1. It sounds like you're trying to c-p commits in a different order than they were pushed to `master`. Don't do that. C-p them in the order they were committed.

**Comment by lfitchett** [comment]
It's not a different order. I made my commit, the daniels went in. Now I want to get just my commit into 1.2, but not daniels. daniels can go in later, but for now daniels commit doesn't work in iotedge

**Comment by arsing** [comment]
Good. So close this PR. Then `reset --hard` the `release/1.2` branch to `main`. It doesn't matter if Daniel's commit is in `release/1.2` or not. The iotedge lockfile gets to decide which commit from the branch is being used.

**Pull request closed without merging**
