### PR TITLE
Update cargo dependencies

### PR DESCRIPTION
**Pull request by gordonwang0**
- Update cargo dependencies to resolve CG issues.
- Update toolchain to 1.65 (consistent with main) because some new dependency versions require newer toolchain.

### CODE REVIEW

**Comment by arsing** [comment]
You should update the dependency versionreqs in Cargo.toml too. eg we depend on an old version of `serde-with` that continues to pulls in an old version of base64.

**Comment by arsing** [comment]
So just to be clear, you checked all the other dependency versionreqs and serde-with was the only one that was old?

**Comment by gordonwang0** [comment]
Actually, I think I'll revert the serde_with version change. Last time we updated dependencies between major versions, we had some issues due to differences in behavior between major versions. Since 1.4 is supposed to be a stable release, I think we should minimize the amount of changes. (And CG isn't complaining about base64, which is the reason for doing this update.)

Let me know if you disagree.

**Comment by arsing** [comment]
Oh right, I mixed up this one and #536. Keeping this one on the same major versions is fine. What I wrote applies to the main branch PR only.

**Review by arsing — APPROVED** [review]

**Pull request merged**
