### PR TITLE
Add Hub mocking to mock-iot-server (#357)

### PR DESCRIPTION
**Pull request by gordonwang0**
- Renames mock-dps-server to mock-iot-server.
- Adds capability to mock Hub get_modules requests. This allow the full provisioning and identity reconciliation flow to be tested.

### CODE REVIEW

**Comment by gordonwang0** [comment]
Cherry-pick this change to release/1.2 to keep the test suite consistent between branches.

**Review by arsing — APPROVED** [review]

**Comment by gordonwang0** [comment]
@arsing Do you know why BTreeSet requires Ord on Module here? Rust 1.47?

**Comment by arsing** [comment]
Yes, 1.56 removed the requirement for the elements to be `Ord` since `new()` doesn't require that.

**Comment by arsing** [comment]
To be clear, you still can't meaningfully use it as a `BTreeSet` for `get` / `insert` without the elements being `Ord`. I see that you don't actually use it in the `main` code, which is why you didn't notice.

**Comment by gordonwang0** [comment]
Got it, thanks. Changed to use HashMap since the ordering doesn't ever matter. Also made a similar fix to main #360

**Pull request merged**
