### PR TITLE
Fix broken plantuml files

### PR DESCRIPTION
**Pull request by micahl**

### CODE REVIEW

**Comment by micahl** [comment]
@eustacea fyi

**Comment by arsing** [comment]
I took the diagram out because nobody could make sense of it and kept asking us questions about it, and it's not important to users of the service.

**Comment by micahl** [comment]
@arsing what questions were asked?

**Comment by arsing** [comment]
I don't think I have the emails any more, but I remember "What is the HLMClient and where can I find it?" "Does newclient mean I have to write a client?" "What is MR and why is it a legacy service?"

The diagram goes into too much detail that is only needed for dev docs. For users the only they need to know about is that IS, KS and CS exist. Also, the edged, EA and EH parts don't belong in this repo's docs.

(I've already removed TPM service's API docs from the web docs and am thinking of downplaying / removing it even further, because people keep thinking that to use TPMs they need to talk to the TPMS instead of KS.)

**Comment by micahl** [comment]
Dropping the reference to the diagram.  Submitting this PR just to fix the old plantuml files which for some reason appear to be missing the opening/ending tags.

**Comment by arsing** [comment]
The move of docs-dev/img/new-component-overview-simple.svg to docs/img/new-component-overview-simple.svg also needs to be reverted.

**Review by arsing — APPROVED** [review]

**Comment by micahl** [comment]
@arsing / @gordonwang0 is the failure with Mariner 2 something that is already known and any reason I should wait for that to be resolved before merging this?

**Comment by arsing** [comment]
@josephknierman Do you know what hostname `pkgworker` is trying to resolve, and what we can do about it?

**Comment by josephknierman** [comment]
@arsing  I think that is due to an issue Mariner 2.0 has in the preview PMC. This line https://github.com/Azure/iot-identity-service/blob/777d313844b821bd9e31935d74162f9cc4c11dff/ci/package.sh#L147 needs to be changed to =n instead of =y I just did a similar fix to a PR in iotedge which seems to have fixes the name resolution issue.

**Pull request merged**
