### PR TITLE
Prepare for Release 1.2.3

### PR DESCRIPTION
**Pull request by yophilav**
- Update aziotctl version to 1.2.3
- Update aziotd version to 1.2.3

### CODE REVIEW

**Comment by arsing** [comment]
You haven't updated aziotd ?

**Comment by yophilav** [comment]
> You haven't updated aziotd ?

From the commit history, we didn't touch the `aziotd` code base. Should I bump its version as well?

**Comment by arsing** [comment]
This is why you sent out an email asking that question. no? And Gordon and I responded that you should bump aziotd too.

**Comment by yophilav** [comment]
Per email discussion, I'll update

> This is why you sent out an email asking that question. no? And Gordon and I responded that you should bump aziotd too.

I just saw your respond. The PR should be up-to-date.

**Review by darobs — APPROVED** [review]

**Review by gordonwang0 — APPROVED** [review]

**Pull request merged**
